### ISSUE TITLE
Wrong number of words?

### ISSUE THREAD

**Issue by denisshevchenko** [TGOlson/bip39#1]
I'm trying to generate 12-words mnemonic:

```
import           Crypto.BIP39

main :: IO ()
main = generateEntropyStdGen S128 >>= (print . entropyToMnemonic)
```

As I see, `S128` corresponds to 12-words mnenomic: https://github.com/TGOlson/bip39/blob/master/lib/Crypto/BIP39.hs#L50. But I got this result:

```
["violin","range","close","admit","belt","strong","update","stick","discover","coyote","palm"]
```

11 words instead of 12. Why?

**Comment by denisshevchenko** [comment]
Moreover, for other values of `Strength` I see the same, for example:

```
["color","half","develop","can","income","ritual","safe","among","blue","any","grain","someone","autumn","vocal"]
```
14 words instead of 15, for `S160`.

**Comment by TGOlson** [comment]
Hey @denisshevchenko, thanks for bringing this up. This is a work in progress, and right now only works for 256 bits of entropy. So the only call that will produce correct results is `generateEntropyStdGen S256`. I should have noted that on the README. If you want to open a pull request to support additional strengths, that'd be greatly appreciated. 

I think the specific issue is [where the checksum is calculated](https://github.com/TGOlson/bip39/blob/master/lib/Crypto/BIP39.hs#L91). The function only works for 256 bit instances because at that point the entropy is a bytestring with a length of 32 bytes, and so the length calculation returns `1` (`32 div 32 == 1`). 

For other sizes the checksum calculation produces 0 bytes -- for example `S128` is stored as a 16 byte bytestring, `16 div 32 == 0`.

I think the fix is to calculate the checksum length in bits, instead of bytes. That way for the 128 bit entropy instance, the code correctly appends a 4 bit checksum.

The sudo-code might look something like this

```
calcChecksum :: Bits -> Bits
calcChecksum bits = takeBits x $ SHA256.hash bits
  where
    x = numBits bits `div` 32
```

**Comment by TGOlson** [comment]
hey @denisshevchenko, should be fixed in the latest master.
